[uccsd/uccgsd] Update test tolerances (#375)
Updating to address non-repeatable tests:


https://github.com/NVIDIA/cudaqx/actions/runs/19416074410/job/55545607521#step:12:6541
```
FAILED libs/solvers/python/tests/test_uccgsd.py::test_solvers_adapt_uccgsd_lih - assert np.False_
 +  where np.False_ = <function isclose at 0x7d33747471f0>(-7.8636041028194565, -7.8638, atol=0.0001)
 +    where <function isclose at 0x7d33747471f0> = np.isclose
```


https://github.com/NVIDIA/cudaqx/actions/runs/19485800654/job/55767775297?pr=344#step:14:129
```
FAILED ../libs/solvers/python/tests/test_uccsd.py::test_uccsd_loops - assert 7 == 6
```

Signed-off-by: Ben Howe <bhowe@nvidia.com>